# Generated by Django 3.1.3 on 2020-11-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201125_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
