# Generated by Django 3.1.3 on 2020-11-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(1, 'Cameras'), (2, 'Accessories'), (3, 'New Arrivals')], default='New Arrivals', max_length=1),
            preserve_default=False,
        ),
    ]
