# Generated by Django 3.1.3 on 2020-12-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201130_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='most_popular',
            field=models.BooleanField(default=False),
        ),
    ]
